/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorreDeControleRouteImport } from './routes/torre-de-controle'
import { Route as SustentabilidadeRouteImport } from './routes/sustentabilidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RdcRouteImport } from './routes/rdc'
import { Route as PecuariaRouteImport } from './routes/pecuaria'
import { Route as OtimizacaoCogsRouteImport } from './routes/otimizacao-cogs'
import { Route as LogisticaRouteImport } from './routes/logistica'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EquipeVendasRouteImport } from './routes/equipe-vendas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CampoRouteImport } from './routes/campo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RdcIdRouteImport } from './routes/rdc_.$id'
import { Route as PecuariaCurralRouteImport } from './routes/pecuaria_.curral'
import { Route as CampoTalhoesRouteImport } from './routes/campo_.talhoes'
import { Route as CampoInsumosRouteImport } from './routes/campo_.insumos'
import { Route as CampoColheitaRouteImport } from './routes/campo_.colheita'
import { Route as CampoCalendarioRouteImport } from './routes/campo_.calendario'
import { Route as CampoTalhoesFieldIdRouteImport } from './routes/campo_.talhoes_.$fieldId'

const TorreDeControleRoute = TorreDeControleRouteImport.update({
  id: '/torre-de-controle',
  path: '/torre-de-controle',
  getParentRoute: () => rootRouteImport,
} as any)
const SustentabilidadeRoute = SustentabilidadeRouteImport.update({
  id: '/sustentabilidade',
  path: '/sustentabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RdcRoute = RdcRouteImport.update({
  id: '/rdc',
  path: '/rdc',
  getParentRoute: () => rootRouteImport,
} as any)
const PecuariaRoute = PecuariaRouteImport.update({
  id: '/pecuaria',
  path: '/pecuaria',
  getParentRoute: () => rootRouteImport,
} as any)
const OtimizacaoCogsRoute = OtimizacaoCogsRouteImport.update({
  id: '/otimizacao-cogs',
  path: '/otimizacao-cogs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaRoute = LogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeVendasRoute = EquipeVendasRouteImport.update({
  id: '/equipe-vendas',
  path: '/equipe-vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoRoute = CampoRouteImport.update({
  id: '/campo',
  path: '/campo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RdcIdRoute = RdcIdRouteImport.update({
  id: '/rdc_/$id',
  path: '/rdc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PecuariaCurralRoute = PecuariaCurralRouteImport.update({
  id: '/pecuaria_/curral',
  path: '/pecuaria/curral',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoTalhoesRoute = CampoTalhoesRouteImport.update({
  id: '/campo_/talhoes',
  path: '/campo/talhoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoInsumosRoute = CampoInsumosRouteImport.update({
  id: '/campo_/insumos',
  path: '/campo/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoColheitaRoute = CampoColheitaRouteImport.update({
  id: '/campo_/colheita',
  path: '/campo/colheita',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoCalendarioRoute = CampoCalendarioRouteImport.update({
  id: '/campo_/calendario',
  path: '/campo/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CampoTalhoesFieldIdRoute = CampoTalhoesFieldIdRouteImport.update({
  id: '/campo_/talhoes_/$fieldId',
  path: '/campo/talhoes/$fieldId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campo': typeof CampoRoute
  '/dashboard': typeof DashboardRoute
  '/equipe-vendas': typeof EquipeVendasRoute
  '/financeiro': typeof FinanceiroRoute
  '/inteligencia': typeof InteligenciaRoute
  '/login': typeof LoginRoute
  '/logistica': typeof LogisticaRoute
  '/otimizacao-cogs': typeof OtimizacaoCogsRoute
  '/pecuaria': typeof PecuariaRoute
  '/rdc': typeof RdcRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sustentabilidade': typeof SustentabilidadeRoute
  '/torre-de-controle': typeof TorreDeControleRoute
  '/campo/calendario': typeof CampoCalendarioRoute
  '/campo/colheita': typeof CampoColheitaRoute
  '/campo/insumos': typeof CampoInsumosRoute
  '/campo/talhoes': typeof CampoTalhoesRoute
  '/pecuaria/curral': typeof PecuariaCurralRoute
  '/rdc/$id': typeof RdcIdRoute
  '/campo/talhoes/$fieldId': typeof CampoTalhoesFieldIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campo': typeof CampoRoute
  '/dashboard': typeof DashboardRoute
  '/equipe-vendas': typeof EquipeVendasRoute
  '/financeiro': typeof FinanceiroRoute
  '/inteligencia': typeof InteligenciaRoute
  '/login': typeof LoginRoute
  '/logistica': typeof LogisticaRoute
  '/otimizacao-cogs': typeof OtimizacaoCogsRoute
  '/pecuaria': typeof PecuariaRoute
  '/rdc': typeof RdcRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sustentabilidade': typeof SustentabilidadeRoute
  '/torre-de-controle': typeof TorreDeControleRoute
  '/campo/calendario': typeof CampoCalendarioRoute
  '/campo/colheita': typeof CampoColheitaRoute
  '/campo/insumos': typeof CampoInsumosRoute
  '/campo/talhoes': typeof CampoTalhoesRoute
  '/pecuaria/curral': typeof PecuariaCurralRoute
  '/rdc/$id': typeof RdcIdRoute
  '/campo/talhoes/$fieldId': typeof CampoTalhoesFieldIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campo': typeof CampoRoute
  '/dashboard': typeof DashboardRoute
  '/equipe-vendas': typeof EquipeVendasRoute
  '/financeiro': typeof FinanceiroRoute
  '/inteligencia': typeof InteligenciaRoute
  '/login': typeof LoginRoute
  '/logistica': typeof LogisticaRoute
  '/otimizacao-cogs': typeof OtimizacaoCogsRoute
  '/pecuaria': typeof PecuariaRoute
  '/rdc': typeof RdcRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sustentabilidade': typeof SustentabilidadeRoute
  '/torre-de-controle': typeof TorreDeControleRoute
  '/campo_/calendario': typeof CampoCalendarioRoute
  '/campo_/colheita': typeof CampoColheitaRoute
  '/campo_/insumos': typeof CampoInsumosRoute
  '/campo_/talhoes': typeof CampoTalhoesRoute
  '/pecuaria_/curral': typeof PecuariaCurralRoute
  '/rdc_/$id': typeof RdcIdRoute
  '/campo_/talhoes_/$fieldId': typeof CampoTalhoesFieldIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campo'
    | '/dashboard'
    | '/equipe-vendas'
    | '/financeiro'
    | '/inteligencia'
    | '/login'
    | '/logistica'
    | '/otimizacao-cogs'
    | '/pecuaria'
    | '/rdc'
    | '/redefinir-senha'
    | '/sustentabilidade'
    | '/torre-de-controle'
    | '/campo/calendario'
    | '/campo/colheita'
    | '/campo/insumos'
    | '/campo/talhoes'
    | '/pecuaria/curral'
    | '/rdc/$id'
    | '/campo/talhoes/$fieldId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campo'
    | '/dashboard'
    | '/equipe-vendas'
    | '/financeiro'
    | '/inteligencia'
    | '/login'
    | '/logistica'
    | '/otimizacao-cogs'
    | '/pecuaria'
    | '/rdc'
    | '/redefinir-senha'
    | '/sustentabilidade'
    | '/torre-de-controle'
    | '/campo/calendario'
    | '/campo/colheita'
    | '/campo/insumos'
    | '/campo/talhoes'
    | '/pecuaria/curral'
    | '/rdc/$id'
    | '/campo/talhoes/$fieldId'
  id:
    | '__root__'
    | '/'
    | '/campo'
    | '/dashboard'
    | '/equipe-vendas'
    | '/financeiro'
    | '/inteligencia'
    | '/login'
    | '/logistica'
    | '/otimizacao-cogs'
    | '/pecuaria'
    | '/rdc'
    | '/redefinir-senha'
    | '/sustentabilidade'
    | '/torre-de-controle'
    | '/campo_/calendario'
    | '/campo_/colheita'
    | '/campo_/insumos'
    | '/campo_/talhoes'
    | '/pecuaria_/curral'
    | '/rdc_/$id'
    | '/campo_/talhoes_/$fieldId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampoRoute: typeof CampoRoute
  DashboardRoute: typeof DashboardRoute
  EquipeVendasRoute: typeof EquipeVendasRoute
  FinanceiroRoute: typeof FinanceiroRoute
  InteligenciaRoute: typeof InteligenciaRoute
  LoginRoute: typeof LoginRoute
  LogisticaRoute: typeof LogisticaRoute
  OtimizacaoCogsRoute: typeof OtimizacaoCogsRoute
  PecuariaRoute: typeof PecuariaRoute
  RdcRoute: typeof RdcRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SustentabilidadeRoute: typeof SustentabilidadeRoute
  TorreDeControleRoute: typeof TorreDeControleRoute
  CampoCalendarioRoute: typeof CampoCalendarioRoute
  CampoColheitaRoute: typeof CampoColheitaRoute
  CampoInsumosRoute: typeof CampoInsumosRoute
  CampoTalhoesRoute: typeof CampoTalhoesRoute
  PecuariaCurralRoute: typeof PecuariaCurralRoute
  RdcIdRoute: typeof RdcIdRoute
  CampoTalhoesFieldIdRoute: typeof CampoTalhoesFieldIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torre-de-controle': {
      id: '/torre-de-controle'
      path: '/torre-de-controle'
      fullPath: '/torre-de-controle'
      preLoaderRoute: typeof TorreDeControleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustentabilidade': {
      id: '/sustentabilidade'
      path: '/sustentabilidade'
      fullPath: '/sustentabilidade'
      preLoaderRoute: typeof SustentabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdc': {
      id: '/rdc'
      path: '/rdc'
      fullPath: '/rdc'
      preLoaderRoute: typeof RdcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecuaria': {
      id: '/pecuaria'
      path: '/pecuaria'
      fullPath: '/pecuaria'
      preLoaderRoute: typeof PecuariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otimizacao-cogs': {
      id: '/otimizacao-cogs'
      path: '/otimizacao-cogs'
      fullPath: '/otimizacao-cogs'
      preLoaderRoute: typeof OtimizacaoCogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof LogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe-vendas': {
      id: '/equipe-vendas'
      path: '/equipe-vendas'
      fullPath: '/equipe-vendas'
      preLoaderRoute: typeof EquipeVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo': {
      id: '/campo'
      path: '/campo'
      fullPath: '/campo'
      preLoaderRoute: typeof CampoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdc_/$id': {
      id: '/rdc_/$id'
      path: '/rdc/$id'
      fullPath: '/rdc/$id'
      preLoaderRoute: typeof RdcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecuaria_/curral': {
      id: '/pecuaria_/curral'
      path: '/pecuaria/curral'
      fullPath: '/pecuaria/curral'
      preLoaderRoute: typeof PecuariaCurralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo_/talhoes': {
      id: '/campo_/talhoes'
      path: '/campo/talhoes'
      fullPath: '/campo/talhoes'
      preLoaderRoute: typeof CampoTalhoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo_/insumos': {
      id: '/campo_/insumos'
      path: '/campo/insumos'
      fullPath: '/campo/insumos'
      preLoaderRoute: typeof CampoInsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo_/colheita': {
      id: '/campo_/colheita'
      path: '/campo/colheita'
      fullPath: '/campo/colheita'
      preLoaderRoute: typeof CampoColheitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo_/calendario': {
      id: '/campo_/calendario'
      path: '/campo/calendario'
      fullPath: '/campo/calendario'
      preLoaderRoute: typeof CampoCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campo_/talhoes_/$fieldId': {
      id: '/campo_/talhoes_/$fieldId'
      path: '/campo/talhoes/$fieldId'
      fullPath: '/campo/talhoes/$fieldId'
      preLoaderRoute: typeof CampoTalhoesFieldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampoRoute: CampoRoute,
  DashboardRoute: DashboardRoute,
  EquipeVendasRoute: EquipeVendasRoute,
  FinanceiroRoute: FinanceiroRoute,
  InteligenciaRoute: InteligenciaRoute,
  LoginRoute: LoginRoute,
  LogisticaRoute: LogisticaRoute,
  OtimizacaoCogsRoute: OtimizacaoCogsRoute,
  PecuariaRoute: PecuariaRoute,
  RdcRoute: RdcRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SustentabilidadeRoute: SustentabilidadeRoute,
  TorreDeControleRoute: TorreDeControleRoute,
  CampoCalendarioRoute: CampoCalendarioRoute,
  CampoColheitaRoute: CampoColheitaRoute,
  CampoInsumosRoute: CampoInsumosRoute,
  CampoTalhoesRoute: CampoTalhoesRoute,
  PecuariaCurralRoute: PecuariaCurralRoute,
  RdcIdRoute: RdcIdRoute,
  CampoTalhoesFieldIdRoute: CampoTalhoesFieldIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
