// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Constantes injetadas no build (vite.config `define`), a partir de
// SUPABASE_URL/SUPABASE_PUBLISHABLE_KEY OU das versões VITE_. Assim o cliente
// funciona mesmo se as chaves foram definidas sem o prefixo VITE_. O guard
// `typeof` mantém tudo seguro em ambientes sem o `define` (ex.: testes).
declare const __SUPABASE_URL__: string;
declare const __SUPABASE_KEY__: string;
const BUILD_URL = typeof __SUPABASE_URL__ !== "undefined" ? __SUPABASE_URL__ : "";
const BUILD_KEY = typeof __SUPABASE_KEY__ !== "undefined" ? __SUPABASE_KEY__ : "";

function createSupabaseClient() {
  // Cliente: só enxerga import.meta.env.VITE_* + as constantes do build (BUILD_*).
  // Servidor (SSR): também process.env.*.
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || BUILD_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    BUILD_KEY;

  const storage = typeof window !== "undefined" ? localStorage : undefined;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    // Modo degradado: NÃO lança aqui. Lançar derrubaria toda página guiada por
    // dados via error boundary (o `supabase` é acessado em hooks/effects no
    // cliente). Em vez disso, cria um client placeholder — queries e realtime
    // falham no nível de rede (tratados pelo React Query / no-op) sem crashar a UI.
    console.error(
      `[Supabase] Variável(is) de ambiente ausente(s): ${missing.join(", ")}. ` +
        `App em modo degradado (sem dados ao vivo) — configure as env vars e refaça o deploy.`,
    );
    return createClient<Database>("https://placeholder.supabase.co", "placeholder-anon-key", {
      auth: { storage, persistSession: false, autoRefreshToken: false },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: { storage, persistSession: true, autoRefreshToken: true },
  });
}

// `true` quando as env vars do Supabase estão presentes. Use para evitar tentar
// realtime/queries quando o app está em modo degradado.
export const isSupabaseConfigured = Boolean(
  (import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || BUILD_URL) &&
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY ||
    BUILD_KEY),
);

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
