// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  const storage = typeof window !== "undefined" ? localStorage : undefined;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    // Modo degradado: NÃO lança aqui. Lançar derrubaria toda página guiada por
    // dados via error boundary (o `supabase` é acessado em hooks/effects no
    // cliente). Em vez disso, cria um client placeholder — queries e realtime
    // falham no nível de rede (tratados pelo React Query / no-op) sem crashar a UI.
    console.error(
      `[Supabase] Variável(is) de ambiente ausente(s): ${missing.join(", ")}. ` +
        `App em modo degradado (sem dados ao vivo) — configure as env vars e refaça o deploy.`,
    );
    return createClient<Database>("https://placeholder.supabase.co", "placeholder-anon-key", {
      auth: { storage, persistSession: false, autoRefreshToken: false },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: { storage, persistSession: true, autoRefreshToken: true },
  });
}

// `true` quando as env vars do Supabase estão presentes. Use para evitar tentar
// realtime/queries quando o app está em modo degradado.
export const isSupabaseConfigured = Boolean(
  (import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL) &&
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY),
);

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
